# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.5
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: bwhippo@gmail.com
author_name: SilentRhetoric
cloud_provider: netlify
contract_name: dechametz
deployment_language: python
preset_name: production
project_name: deChametz

